name: r-dashboard-env
channels:
  - conda-forge
  - r
dependencies:
  - r
  - r-cowplot
  - r-dashboardthemes
  - r-dplyr
  - r-extrafont
  - r-ggmap
  - r-ggplot2
  - r-gridextra
  - r-htmltools
  - r-leaflet
  - r-lubridate
  - r-magick
  - r-png
  - r-readr
  - r-readxl
  - r-shiny
  - r-shinydashboard
  - r-slickr
  - r-tidyr
  - r-tidyverse
  - r-treemapify
